
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12.18.3'
git:
  depth: 3
script:
  - npm test
deploy:
    provider: elasticbeanstalk
    access_key_id: "$AWSAccessKeyId"
    secret_access_key: "$AWSSecretKey"
    region: "us-east-2"
    app: "Terapify"
    env: "Terapify-env"
    bucket_name: "terapify-s3-bucket"
    on:
      branch: main